version: '3.8'
services:
  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NUXT_HOST=0.0.0.0
      - API_BASE_URL=http://backend:3001
    depends_on:
      - backend